#security:
#    firewalls:
#        frontend:
#            pattern: ^/
#            anonymous: ~
#            form_login:
#                login_path: /login
#                check_path: /login_check
#                default_target_path: /
#            logout:
#                path: logout
#                target: login
#    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#
#    providers:
#        usuarios:
#            entity: { class: AppBundle\Entity\Usuario, property: usuario }
#    encoders:
#        AppBundle\Entity\Usuario:  { algorithm: sha512, iterations: 5, encode_as_base64: false }


security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12
# access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Usuario
                property: usuario
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: /logout