base_index:
    path:     /
    defaults: { _controller: "AppBundle:base:index" }
    methods:  GET

base_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:base:show" }
    methods:  GET

base_new:
    path:     /new
    defaults: { _controller: "AppBundle:base:new" }
    methods:  [GET, POST]

base_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:base:edit" }
    methods:  [GET, POST]

base_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:base:delete" }
    methods:  DELETE
