chofer_index:
    path:     /
    defaults: { _controller: "AppBundle:Chofer:index" }
    methods:  GET

chofer_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Chofer:show" }
    methods:  GET

chofer_new:
    path:     /new
    defaults: { _controller: "AppBundle:Chofer:new" }
    methods:  [GET, POST]

chofer_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Chofer:edit" }
    methods:  [GET, POST]

chofer_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Chofer:delete" }
    methods:  DELETE
