escogidaturno_index:
    path:     /
    defaults: { _controller: "AppBundle:EscogidaTurno:index" }
    methods:  GET

escogidaturno_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:EscogidaTurno:show" }
    methods:  GET

escogidaturno_new:
    path:     /new
    defaults: { _controller: "AppBundle:EscogidaTurno:new" }
    methods:  [GET, POST]

escogidaturno_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:EscogidaTurno:edit" }
    methods:  [GET, POST]

escogidaturno_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:EscogidaTurno:delete" }
    methods:  DELETE
