gps_index:
    path:     /
    defaults: { _controller: "AppBundle:GPS:index" }
    methods:  GET

gps_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:GPS:show" }
    methods:  GET

gps_new:
    path:     /new
    defaults: { _controller: "AppBundle:GPS:new" }
    methods:  [GET, POST]

gps_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:GPS:edit" }
    methods:  [GET, POST]

gps_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:GPS:delete" }
    methods:  DELETE
