hojaruta_index:
    path:     /
    defaults: { _controller: "AppBundle:HojaRuta:index" }
    methods:  GET

hojaruta_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:HojaRuta:show" }
    methods:  GET

hojaruta_new:
    path:     /new
    defaults: { _controller: "AppBundle:HojaRuta:new" }
    methods:  [GET, POST]

hojaruta_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:HojaRuta:edit" }
    methods:  [GET, POST]

hojaruta_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:HojaRuta:delete" }
    methods:  DELETE
