nuevo_index:
    path:     /
    defaults: { _controller: "AppBundle:Nuevo:index" }
    methods:  GET

nuevo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Nuevo:show" }
    methods:  GET

nuevo_new:
    path:     /new
    defaults: { _controller: "AppBundle:Nuevo:new" }
    methods:  [GET, POST]

nuevo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Nuevo:edit" }
    methods:  [GET, POST]

nuevo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Nuevo:delete" }
    methods:  DELETE
