omnibus_index:
    path:     /
    defaults: { _controller: "AppBundle:Omnibus:index" }
    methods:  GET

omnibus_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Omnibus:show" }
    methods:  GET

omnibus_new:
    path:     /new
    defaults: { _controller: "AppBundle:Omnibus:new" }
    methods:  [GET, POST]

omnibus_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Omnibus:edit" }
    methods:  [GET, POST]

omnibus_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Omnibus:delete" }
    methods:  DELETE
