recaudacion_index:
    path:     /
    defaults: { _controller: "AppBundle:Recaudacion:index" }
    methods:  GET

recaudacion_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Recaudacion:reporte" }
    methods:  GET

recaudacion_new:
    path:     /new
    defaults: { _controller: "AppBundle:Recaudacion:new" }
    methods:  [GET, POST]

recaudacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Recaudacion:edit" }
    methods:  [GET, POST]

recaudacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Recaudacion:delete" }
    methods:  DELETE
