tarjeta_combustible_index:
    path:     /
    defaults: { _controller: "AppBundle:Tarjeta_combustible:index" }
    methods:  GET

tarjeta_combustible_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Tarjeta_combustible:show" }
    methods:  GET

tarjeta_combustible_new:
    path:     /new
    defaults: { _controller: "AppBundle:Tarjeta_combustible:new" }
    methods:  [GET, POST]

tarjeta_combustible_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Tarjeta_combustible:edit" }
    methods:  [GET, POST]

tarjeta_combustible_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Tarjeta_combustible:delete" }
    methods:  DELETE
