tipoincidencia_index:
    path:     /
    defaults: { _controller: "AppBundle:TipoIncidencia:index" }
    methods:  GET

tipoincidencia_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:TipoIncidencia:show" }
    methods:  GET

tipoincidencia_new:
    path:     /new
    defaults: { _controller: "AppBundle:TipoIncidencia:new" }
    methods:  [GET, POST]

tipoincidencia_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:TipoIncidencia:edit" }
    methods:  [GET, POST]

tipoincidencia_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:TipoIncidencia:delete" }
    methods:  DELETE
