tipocombustible_index:
    path:     /
    defaults: { _controller: "AppBundle:TipoCombustible:index" }
    methods:  GET

tipocombustible_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:TipoCombustible:show" }
    methods:  GET

tipocombustible_new:
    path:     /new
    defaults: { _controller: "AppBundle:TipoCombustible:new" }
    methods:  [GET, POST]

tipocombustible_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:TipoCombustible:edit" }
    methods:  [GET, POST]

tipocombustible_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:TipoCombustible:delete" }
    methods:  DELETE
