#tipo_horas_trabajo_index:
#    path:     /
#    defaults: { _controller: "AppBundle:Tipo_horas_trabajo:index" }
#    methods:  GET
#
#tipo_horas_trabajo_show:
#    path:     /{id}/show
#    defaults: { _controller: "AppBundle:Tipo_horas_trabajo:show" }
#    methods:  GET
#
#tipo_horas_trabajo_new:
#    path:     /new
#    defaults: { _controller: "AppBundle:Tipo_horas_trabajo:new" }
#    methods:  [GET, POST]
#
#tipo_horas_trabajo_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "AppBundle:Tipo_horas_trabajo:edit" }
#    methods:  [GET, POST]
#
#tipo_horas_trabajo_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "AppBundle:Tipo_horas_trabajo:delete" }
#    methods:  DELETE
